const products = [
    {
      id: 1,
      name: "Wireless Earbuds",
      description: "High-quality wireless earbuds with noise cancellation.",
      category: "Electronics",
      price: 49.99,
      availableStock: 120,
      stockQuantity: 120,
    },
    {
      id: 2,
      name: "Smartphone Stand",
      description: "Adjustable stand for all smartphones and tablets.",
      category: "Accessories",
      price: 14.99,
      availableStock: 200,
      stockQuantity: 200,
    },
    {
      id: 3,
      name: "Gaming Keyboard",
      description: "RGB backlit gaming keyboard with mechanical keys.",
      category: "Electronics",
      price: 79.99,
      availableStock: 80,
      stockQuantity: 80,
    },
    {
      id: 4,
      name: "Yoga Mat",
      description: "Non-slip yoga mat for fitness and exercise.",
      category: "Sports",
      price: 19.99,
      availableStock: 150,
      stockQuantity: 150,
    },
    {
      id: 5,
      name: "Water Bottle",
      description: "Insulated water bottle keeps drinks cold for 12 hours.",
      category: "Home",
      price: 24.99,
      availableStock: 50,
      stockQuantity: 50,
    },
    {
      id: 6,
      name: "Bluetooth Speaker",
      description: "Portable Bluetooth speaker with deep bass.",
      category: "Electronics",
      price: 39.99,
      availableStock: 95,
      stockQuantity: 95,
    },
    {
      id: 7,
      name: "Running Shoes",
      description: "Comfortable and durable running shoes for men and women.",
      category: "Sports",
      price: 69.99,
      availableStock: 110,
      stockQuantity: 110,
    },
    {
      id: 8,
      name: "LED Desk Lamp",
      description: "Adjustable LED desk lamp with USB charging port.",
      category: "Home",
      price: 29.99,
      availableStock: 75,
      stockQuantity: 75,
    },
    {
      id: 9,
      name: "Wireless Mouse",
      description: "Ergonomic wireless mouse with adjustable DPI.",
      category: "Electronics",
      price: 25.99,
      availableStock: 150,
      stockQuantity: 150,
    },
    {
      id: 10,
      name: "Notebook",
      description: "Classic lined notebook for everyday use.",
      category: "Stationery",
      price: 9.99,
      availableStock: 300,
      stockQuantity: 300,
    },
    {
      id: 11,
      name: "Travel Backpack",
      description: "Water-resistant travel backpack with multiple compartments.",
      category: "Accessories",
      price: 59.99,
      availableStock: 60,
      stockQuantity: 60,
    },
    {
      id: 12,
      name: "Electric Toothbrush",
      description: "Rechargeable electric toothbrush with timer.",
      category: "Health",
      price: 34.99,
      availableStock: 90,
      stockQuantity: 90,
    },
    {
      id: 13,
      name: "Hair Dryer",
      description: "Compact and lightweight hair dryer with multiple settings.",
      category: "Beauty",
      price: 49.99,
      availableStock: 70,
      stockQuantity: 70,
    },
    {
      id: 14,
      name: "Kitchen Knife Set",
      description: "Professional kitchen knife set with stainless steel blades.",
      category: "Home",
      price: 89.99,
      availableStock: 30,
      stockQuantity: 30,
    },
    {
      id: 15,
      name: "Wireless Charger",
      description: "Fast wireless charger compatible with all Qi-enabled devices.",
      category: "Electronics",
      price: 29.99,
      availableStock: 100,
      stockQuantity: 100,
    },
  ];
  
  export default products;
  